- name: Create condor and cloud directories in /scratch
  file: 
   path: "{{ item }}"
   recurse: yes
   state: directory
  with_items:
    - /scratch/etc/condor
    - /scratch/var/log/condor
    - /scratch/var/lib/condor
    - /scratch/etc/cloud
    - /scratch/var/lock/condor
    - /scratch/var/run/condor