---
- hosts: container_config
  gather_facts: yes
  roles:
    - { role: prepare-scratch-dir}
    - { role: add-container-config } 
    - { role: cloud-site }
    - { role: git-credentials }
    - { role: htcondor }
